const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const data={overview:{title:"Центр управлінської аналітики",sub:"Зведені показники · Демо-дані"},processes:{title:"Аналітика процесів",sub:"Розріз · процеси та їх KPI"},employees:{title:"Аналітика працівників",sub:"Рейтинг · індивідуальні KPI"},reports:{title:"Звіти та зрізи",sub:"Конструктор · майбутній модуль"},settings:{title:"Налаштування",sub:"Система · доступ та конфігурація"}};
let view="overview";
function heading(v){return `<div class="page-heading"><p>${data[v].sub}</p><h2>${data[v].title}</h2></div>`}
function metrics(){return `<div class="metric-grid">${[["Опрацьовано","1 284","+12.8%"],["Завершено","1 198","+8.4%"],["Середній час","42 хв","−6.2%"],["Ефективність","93.3%","+4.7%"]].map(x=>`<div class="metric-card"><span>${x[0]}</span><strong>${x[1]}</strong><b class="positive">${x[2]} до попереднього місяця</b></div>`).join("")}</div>`}
function table(){return `<table class="table"><thead><tr><th>Процес</th><th>Операцій</th><th>KPI</th><th>Динаміка</th></tr></thead><tbody>${[["Trade-in",438,"96.4%","↑ 11.2%"],["PP",352,"92.8%","↑ 7.5%"],["SERVICE",286,"89.1%","↑ 4.2%"],["UPGRADE",208,"95.7%","↑ 13.8%"]].map(r=>`<tr><td>${r[0]}</td><td>${r[1]}</td><td>${r[2]}</td><td class="positive">${r[3]}</td></tr>`).join("")}</tbody></table>`}
function render(){const p=$("#page-container");$("#page-title").textContent={overview:"Огляд",processes:"Процеси",employees:"Працівники",reports:"Звіти",settings:"Налаштування"}[view];$$(".nav-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));if(view==="overview")p.innerHTML=heading(view)+metrics()+`<div class="dashboard-grid"><div class="panel"><h3>Динаміка активності</h3><p>Заготовка під часовий графік</p><div class="chart-placeholder">${[45,60,52,75,66,85,78,92,88,100,94,110].map(h=>`<i style="height:${h}%"></i>`).join("")}</div></div><div class="panel"><h3>Структура процесів</h3><p>Заготовка під кругову діаграму</p><div class="donut"></div></div></div><div class="panel"><h3>Ключові KPI за напрямами</h3>${table()}</div>`;else if(view==="processes")p.innerHTML=heading(view)+`<div class="process-grid">${["Trade-in","PP","SERVICE","UPGRADE","Новий процес","Ще один процес"].map((x,i)=>`<div class="panel"><h3>${x}</h3><p>Заготовка для окремих метрик, SLA, конверсії та часових графіків.</p><strong class="positive">KPI: ${96-i*2}%</strong></div>`).join("")}</div>`;else if(view==="employees")p.innerHTML=heading(view)+`<div class="panel"><h3>Командні показники</h3>${table()}</div>`;else if(view==="reports")p.innerHTML=heading(view)+`<div class="report-grid">${["Місячний звіт","Звіт по працівнику","Порівняння періодів","Керівницький звіт"].map(x=>`<div class="report-card"><h3>${x}</h3><p>Готове місце під майбутній звіт, фільтри та експорт даних.</p></div>`).join("")}</div>`;else p.innerHTML=heading(view)+`<div class="panel"><h3>Демо-режим</h3><p>Зараз авторизація локальна: Admin / Admin. Firebase не використовується, щоб можна було одразу протестувати інтерфейс.</p></div>`}
$("#login-form").onsubmit=e=>{e.preventDefault();if($("#email").value==="Admin"&&$("#password").value==="Admin"){sessionStorage.demo="1";$("#auth-view").classList.add("hidden");$("#dashboard-view").classList.remove("hidden");render()}else $("#auth-error").textContent="Невірний логін або пароль. Спробуйте Admin / Admin."};
$("#main-nav").onclick=e=>{let b=e.target.closest(".nav-item");if(b){view=b.dataset.view;render()}};
$("#logout-btn").onclick=()=>{sessionStorage.removeItem("demo");location.reload()};
if(sessionStorage.demo){$("#auth-view").classList.add("hidden");$("#dashboard-view").classList.remove("hidden");render()}